# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'test_usercmp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'UsercentricsUI', '2.16.0'
  # Pods for test_usercmp

end
